import { createRequire } from 'module';
import fs from 'fs';
const req = createRequire(import.meta.url);
const { chromium } = req('playwright-core');
const out = [];
(async () => {
  const b = await chromium.launch({ executablePath: 'C:/Users/Lenovo/.agent-browser/browsers/chrome-152.0.7977.82/chrome.exe', headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  await p.addInitScript(() => sessionStorage.setItem('mneme-anno', '1'));
  await p.goto('http://127.0.0.1:8491/', { waitUntil: 'load' });
  await p.fill('#t', 'mneme'); await p.click('#f button');
  await p.waitForSelector('.st-title', { timeout: 20000 });
  await p.waitForTimeout(900);
  const st0 = await p.evaluate(() => !!document.querySelector('.bgm'));
  await p.click('.bgm-btn'); await p.waitForTimeout(900);
  const play = await p.evaluate(() => { const a = document.querySelector('.bgm audio'); return { paused: a?.paused, vol: a?.volume, loop: a?.loop, t: Math.round(a?.currentTime ?? 0) }; });
  out.push('控件存在: ' + st0 + ' | 播放态: ' + JSON.stringify(play));
  await p.hover('.bgm'); await p.waitForTimeout(300);
  await p.evaluate(() => { const v = document.querySelector('.bgm-vol'); v.value = 0.6; v.dispatchEvent(new Event('input', { bubbles: true })); });
  await p.waitForTimeout(300);
  out.push('音量调至: ' + await p.evaluate(() => document.querySelector('.bgm audio')?.volume));
  await p.click('.pref-hint'); await p.waitForTimeout(400);
  out.push('偏好面板 BGM 开关: ' + await p.$eval('.pref-row:nth-child(4) input', e => e.checked).catch(() => 'n/a'));
  await p.keyboard.press('Escape'); await p.waitForTimeout(300);
  await p.reload(); await p.waitForTimeout(1500);
  const resume = await p.evaluate(() => { const a = document.querySelector('.bgm audio'); return { on: JSON.parse(localStorage.getItem('mneme-bgm')).on, playing: a && !a.paused }; });
  out.push('刷新自动续播: ' + JSON.stringify(resume));
  await p.hover('.bgm'); await p.waitForTimeout(400);
  await p.screenshot({ path: 'C:/Users/Lenovo/.workbuddy/tmp/v45-bgm.png', clip: { x: 1100, y: 640, width: 340, height: 260 } });
  out.push('无报错: ' + (errs.length === 0 ? 'OK' : errs[0]));
  await b.close();
  fs.writeFileSync('C:/Users/Lenovo/.workbuddy/tmp/v45-result.txt', out.join('\n'));
})().catch(e => fs.writeFileSync('C:/Users/Lenovo/.workbuddy/tmp/v45-result.txt', 'ERR ' + e.message));
